// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFSchools.Api.Data;

#nullable disable

namespace MyFSchools.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306093855_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFSchools.Api.Models.Child", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = "c-001",
                            AvatarUrl = "https://i.pravatar.cc/150?u=c1",
                            ClassName = "3A1",
                            FullName = "Nguyễn Minh An",
                            UserId = "u-001"
                        },
                        new
                        {
                            Id = "c-002",
                            AvatarUrl = "https://i.pravatar.cc/150?u=c2",
                            ClassName = "5B2",
                            FullName = "Nguyễn Thu Hà",
                            UserId = "u-001"
                        },
                        new
                        {
                            Id = "c-003",
                            AvatarUrl = "https://i.pravatar.cc/150?u=c3",
                            ClassName = "4C3",
                            FullName = "Trần Quốc Bảo",
                            UserId = "u-002"
                        },
                        new
                        {
                            Id = "c-004",
                            AvatarUrl = "https://i.pravatar.cc/150?u=c4",
                            ClassName = "2A1",
                            FullName = "Trần Khánh Linh",
                            UserId = "u-002"
                        },
                        new
                        {
                            Id = "c-005",
                            AvatarUrl = "https://i.pravatar.cc/150?u=c5",
                            ClassName = "1B1",
                            FullName = "Lê Hoàng Nam",
                            UserId = "u-003"
                        },
                        new
                        {
                            Id = "c-006",
                            AvatarUrl = "https://i.pravatar.cc/150?u=c6",
                            ClassName = "3A1",
                            FullName = "Lê Thanh Phương",
                            UserId = "u-003"
                        });
                });

            modelBuilder.Entity("MyFSchools.Api.Models.ChildClub", b =>
                {
                    b.Property<string>("ChildId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClubId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ChildId", "ClubId");

                    b.HasIndex("ClubId");

                    b.ToTable("ChildClubs");

                    b.HasData(
                        new
                        {
                            ChildId = "c-001",
                            ClubId = "cl-1"
                        },
                        new
                        {
                            ChildId = "c-001",
                            ClubId = "cl-2"
                        },
                        new
                        {
                            ChildId = "c-002",
                            ClubId = "cl-3"
                        },
                        new
                        {
                            ChildId = "c-003",
                            ClubId = "cl-1"
                        },
                        new
                        {
                            ChildId = "c-003",
                            ClubId = "cl-4"
                        },
                        new
                        {
                            ChildId = "c-004",
                            ClubId = "cl-2"
                        },
                        new
                        {
                            ChildId = "c-005",
                            ClubId = "cl-5"
                        },
                        new
                        {
                            ChildId = "c-005",
                            ClubId = "cl-3"
                        },
                        new
                        {
                            ChildId = "c-006",
                            ClubId = "cl-4"
                        },
                        new
                        {
                            ChildId = "c-006",
                            ClubId = "cl-2"
                        });
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Club", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MemberCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = "cl-1",
                            Category = "Học thuật",
                            MemberCount = 3,
                            Name = "Câu lạc bộ Toán học"
                        },
                        new
                        {
                            Id = "cl-2",
                            Category = "Thể thao",
                            MemberCount = 3,
                            Name = "Câu lạc bộ Bóng đá"
                        },
                        new
                        {
                            Id = "cl-3",
                            Category = "Nghệ thuật",
                            MemberCount = 2,
                            Name = "Câu lạc bộ Mỹ thuật"
                        },
                        new
                        {
                            Id = "cl-4",
                            Category = "Khoa học",
                            MemberCount = 2,
                            Name = "Câu lạc bộ Khoa học"
                        },
                        new
                        {
                            Id = "cl-5",
                            Category = "Nghệ thuật",
                            MemberCount = 2,
                            Name = "Câu lạc bộ Âm nhạc"
                        });
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Time")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = "ev-1",
                            Color = "blue",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventName = "Ngày hội khoa học",
                            Location = "Sân trường",
                            Time = "08:00 - 11:00"
                        },
                        new
                        {
                            Id = "ev-2",
                            Color = "green",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventName = "Hội trại cuối năm",
                            Location = "Công viên Gia Định",
                            Time = "07:00 - 17:00"
                        },
                        new
                        {
                            Id = "ev-3",
                            Color = "orange",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventName = "Văn nghệ chào xuân",
                            Location = "Hội trường A",
                            Time = "14:00 - 16:30"
                        },
                        new
                        {
                            Id = "ev-4",
                            Color = "red",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventName = "Giải thể thao học sinh",
                            Location = "Sân vận động",
                            Time = "07:30 - 11:30"
                        },
                        new
                        {
                            Id = "ev-5",
                            Color = "purple",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventName = "Triển lãm mỹ thuật",
                            Location = "Phòng trưng bày",
                            Time = "09:00 - 12:00"
                        });
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Form", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("UserId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = "f-1",
                            ChildId = "c-001",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = "05/01/2025",
                            Reason = "Gia đình có việc đột xuất",
                            Status = "Đã duyệt",
                            Title = "Đơn xin nghỉ học",
                            Type = "xin nghỉ học",
                            UserId = "u-001"
                        },
                        new
                        {
                            Id = "f-2",
                            ChildId = "c-002",
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = "10/01/2025",
                            Reason = "Tham gia hội trại trường",
                            Status = "Chờ duyệt",
                            Title = "Đơn xin ngoại khóa",
                            Type = "xin ngoại khóa",
                            UserId = "u-001"
                        },
                        new
                        {
                            Id = "f-3",
                            ChildId = "c-003",
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = "12/01/2025",
                            Reason = "Nhà chuyển chỗ, đi lại khó khăn",
                            Status = "Từ chối",
                            Title = "Đơn xin chuyển lớp",
                            Type = "xin chuyển lớp",
                            UserId = "u-002"
                        },
                        new
                        {
                            Id = "f-4",
                            ChildId = "c-004",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = "15/01/2025",
                            Reason = "Con bị ốm cần nghỉ ngơi tại nhà",
                            Status = "Đã duyệt",
                            Title = "Đơn xin nghỉ học",
                            Type = "xin nghỉ học",
                            UserId = "u-002"
                        },
                        new
                        {
                            Id = "f-5",
                            ChildId = "c-005",
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = "18/01/2025",
                            Reason = "Con tham dự đám cưới của người thân",
                            Status = "Chờ duyệt",
                            Title = "Đơn xin nghỉ học",
                            Type = "xin nghỉ học",
                            UserId = "u-003"
                        });
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Grade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Average")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Term")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = "gr-1",
                            Average = 9.2m,
                            ChildId = "c-001",
                            Status = "Passed",
                            Subject = "Toán học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-2",
                            Average = 7.4m,
                            ChildId = "c-001",
                            Status = "Passed",
                            Subject = "Ngữ văn",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-3",
                            Average = 9.0m,
                            ChildId = "c-001",
                            Status = "Passed",
                            Subject = "Tiếng Anh",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-4",
                            Average = 7.2m,
                            ChildId = "c-001",
                            Status = "Passed",
                            Subject = "Khoa học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-5",
                            Average = 7.9m,
                            ChildId = "c-001",
                            Status = "Passed",
                            Subject = "Lịch sử",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-6",
                            Average = 9.2m,
                            ChildId = "c-001",
                            Status = "Passed",
                            Subject = "Địa lý",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-7",
                            Average = 9.2m,
                            ChildId = "c-002",
                            Status = "Passed",
                            Subject = "Toán học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-8",
                            Average = 7.4m,
                            ChildId = "c-002",
                            Status = "Passed",
                            Subject = "Ngữ văn",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-9",
                            Average = 9.0m,
                            ChildId = "c-002",
                            Status = "Passed",
                            Subject = "Tiếng Anh",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-10",
                            Average = 7.2m,
                            ChildId = "c-002",
                            Status = "Passed",
                            Subject = "Khoa học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-11",
                            Average = 7.9m,
                            ChildId = "c-002",
                            Status = "Passed",
                            Subject = "Lịch sử",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-12",
                            Average = 9.2m,
                            ChildId = "c-002",
                            Status = "Passed",
                            Subject = "Địa lý",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-13",
                            Average = 9.2m,
                            ChildId = "c-003",
                            Status = "Passed",
                            Subject = "Toán học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-14",
                            Average = 7.4m,
                            ChildId = "c-003",
                            Status = "Passed",
                            Subject = "Ngữ văn",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-15",
                            Average = 9.0m,
                            ChildId = "c-003",
                            Status = "Passed",
                            Subject = "Tiếng Anh",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-16",
                            Average = 7.2m,
                            ChildId = "c-003",
                            Status = "Passed",
                            Subject = "Khoa học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-17",
                            Average = 7.9m,
                            ChildId = "c-003",
                            Status = "Passed",
                            Subject = "Lịch sử",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-18",
                            Average = 9.2m,
                            ChildId = "c-003",
                            Status = "Passed",
                            Subject = "Địa lý",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-19",
                            Average = 9.2m,
                            ChildId = "c-004",
                            Status = "Passed",
                            Subject = "Toán học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-20",
                            Average = 7.4m,
                            ChildId = "c-004",
                            Status = "Passed",
                            Subject = "Ngữ văn",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-21",
                            Average = 9.0m,
                            ChildId = "c-004",
                            Status = "Passed",
                            Subject = "Tiếng Anh",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-22",
                            Average = 7.2m,
                            ChildId = "c-004",
                            Status = "Passed",
                            Subject = "Khoa học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-23",
                            Average = 7.9m,
                            ChildId = "c-004",
                            Status = "Passed",
                            Subject = "Lịch sử",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-24",
                            Average = 9.2m,
                            ChildId = "c-004",
                            Status = "Passed",
                            Subject = "Địa lý",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-25",
                            Average = 9.2m,
                            ChildId = "c-005",
                            Status = "Passed",
                            Subject = "Toán học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-26",
                            Average = 7.4m,
                            ChildId = "c-005",
                            Status = "Passed",
                            Subject = "Ngữ văn",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-27",
                            Average = 9.0m,
                            ChildId = "c-005",
                            Status = "Passed",
                            Subject = "Tiếng Anh",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-28",
                            Average = 7.2m,
                            ChildId = "c-005",
                            Status = "Passed",
                            Subject = "Khoa học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-29",
                            Average = 7.9m,
                            ChildId = "c-005",
                            Status = "Passed",
                            Subject = "Lịch sử",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-30",
                            Average = 9.2m,
                            ChildId = "c-005",
                            Status = "Passed",
                            Subject = "Địa lý",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-31",
                            Average = 9.2m,
                            ChildId = "c-006",
                            Status = "Passed",
                            Subject = "Toán học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-32",
                            Average = 7.4m,
                            ChildId = "c-006",
                            Status = "Passed",
                            Subject = "Ngữ văn",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-33",
                            Average = 9.0m,
                            ChildId = "c-006",
                            Status = "Passed",
                            Subject = "Tiếng Anh",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-34",
                            Average = 7.2m,
                            ChildId = "c-006",
                            Status = "Passed",
                            Subject = "Khoa học",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-35",
                            Average = 7.9m,
                            ChildId = "c-006",
                            Status = "Passed",
                            Subject = "Lịch sử",
                            Term = "Học kỳ 1 - 2024-2025"
                        },
                        new
                        {
                            Id = "gr-36",
                            Average = 9.2m,
                            ChildId = "c-006",
                            Status = "Passed",
                            Subject = "Địa lý",
                            Term = "Học kỳ 1 - 2024-2025"
                        });
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = "n-1",
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Học phí học kỳ 2 đã đến hạn nộp.",
                            Title = "Thông báo học phí HK2",
                            Type = "Hệ thống",
                            UserId = "u-001"
                        },
                        new
                        {
                            Id = "n-2",
                            CreatedAt = new DateTime(2025, 1, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Kết quả học tập tháng 1 đã được cập nhật.",
                            Title = "Kết quả học tập tháng 1",
                            Type = "Học tập",
                            UserId = "u-001"
                        },
                        new
                        {
                            Id = "n-3",
                            CreatedAt = new DateTime(2025, 1, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Hội trại cuối năm sẽ diễn ra vào ngày 21/1.",
                            Title = "Sự kiện sắp diễn ra",
                            Type = "Sự kiện",
                            UserId = "u-002"
                        },
                        new
                        {
                            Id = "n-4",
                            CreatedAt = new DateTime(2025, 1, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Lịch kiểm tra giữa kỳ đã được đăng tải.",
                            Title = "Lịch kiểm tra giữa kỳ",
                            Type = "Học tập",
                            UserId = "u-002"
                        },
                        new
                        {
                            Id = "n-5",
                            CreatedAt = new DateTime(2025, 1, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Đơn xin nghỉ của con bạn đã được phê duyệt.",
                            Title = "Đơn xin nghỉ đã được duyệt",
                            Type = "Hệ thống",
                            UserId = "u-003"
                        });
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Schedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Teacher")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Term")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = "sch-1",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.201",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV02",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-2",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.202",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV03",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-3",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.203",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV04",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-4",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.204",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV05",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-5",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.205",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV06",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-6",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.206",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV07",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-7",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.207",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV08",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-8",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.208",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV09",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-9",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.209",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV10",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-10",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.210",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV11",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-11",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.211",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV12",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-12",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.212",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV13",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-13",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.213",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV14",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-14",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.214",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV15",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-15",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.215",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV01",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-16",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.216",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV02",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-17",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.217",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV03",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-18",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.218",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV04",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-19",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.219",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV05",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-20",
                            ClassName = "3A1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.200",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV06",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-21",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 2",
                            Room = "P.201",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV07",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-22",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 2",
                            Room = "P.202",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV08",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-23",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 2",
                            Room = "P.203",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV09",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-24",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 2",
                            Room = "P.204",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV10",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-25",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 3",
                            Room = "P.205",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV11",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-26",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 3",
                            Room = "P.206",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV12",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-27",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 3",
                            Room = "P.207",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV13",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-28",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 3",
                            Room = "P.208",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV14",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-29",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 4",
                            Room = "P.209",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV15",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-30",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 4",
                            Room = "P.210",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV01",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-31",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 4",
                            Room = "P.211",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV02",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-32",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 4",
                            Room = "P.212",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV03",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-33",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 5",
                            Room = "P.213",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV04",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-34",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 5",
                            Room = "P.214",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV05",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-35",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 5",
                            Room = "P.215",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV06",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-36",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 5",
                            Room = "P.216",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV07",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-37",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 6",
                            Room = "P.217",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV08",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-38",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 6",
                            Room = "P.218",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV09",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-39",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 6",
                            Room = "P.219",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV10",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-40",
                            ClassName = "5B2",
                            DayOfWeek = "Thứ 6",
                            Room = "P.200",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV11",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-41",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 2",
                            Room = "P.201",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV12",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-42",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 2",
                            Room = "P.202",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV13",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-43",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 2",
                            Room = "P.203",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV14",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-44",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 2",
                            Room = "P.204",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV15",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-45",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 3",
                            Room = "P.205",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV01",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-46",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 3",
                            Room = "P.206",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV02",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-47",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 3",
                            Room = "P.207",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV03",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-48",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 3",
                            Room = "P.208",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV04",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-49",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 4",
                            Room = "P.209",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV05",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-50",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 4",
                            Room = "P.210",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV06",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-51",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 4",
                            Room = "P.211",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV07",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-52",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 4",
                            Room = "P.212",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV08",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-53",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 5",
                            Room = "P.213",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV09",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-54",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 5",
                            Room = "P.214",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV10",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-55",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 5",
                            Room = "P.215",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV11",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-56",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 5",
                            Room = "P.216",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV12",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-57",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 6",
                            Room = "P.217",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV13",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-58",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 6",
                            Room = "P.218",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV14",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-59",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 6",
                            Room = "P.219",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV15",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-60",
                            ClassName = "4C3",
                            DayOfWeek = "Thứ 6",
                            Room = "P.200",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV01",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-61",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.201",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV02",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-62",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.202",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV03",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-63",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.203",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV04",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-64",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.204",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV05",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-65",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.205",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV06",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-66",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.206",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV07",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-67",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.207",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV08",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-68",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.208",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV09",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-69",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.209",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV10",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-70",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.210",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV11",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-71",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.211",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV12",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-72",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.212",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV13",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-73",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.213",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV14",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-74",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.214",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV15",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-75",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.215",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV01",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-76",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.216",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV02",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-77",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.217",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV03",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-78",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.218",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV04",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-79",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.219",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV05",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-80",
                            ClassName = "2A1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.200",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV06",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-81",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.201",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV07",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-82",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.202",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV08",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-83",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.203",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV09",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-84",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 2",
                            Room = "P.204",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV10",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-85",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.205",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV11",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-86",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.206",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV12",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-87",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.207",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV13",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-88",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 3",
                            Room = "P.208",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV14",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-89",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.209",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV15",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-90",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.210",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV01",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-91",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.211",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV02",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-92",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 4",
                            Room = "P.212",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV03",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-93",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.213",
                            Slot = 1,
                            Subject = "Lịch sử",
                            Teacher = "GV04",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-94",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.214",
                            Slot = 2,
                            Subject = "Địa lý",
                            Teacher = "GV05",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-95",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.215",
                            Slot = 3,
                            Subject = "Đạo đức",
                            Teacher = "GV06",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-96",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 5",
                            Room = "P.216",
                            Slot = 4,
                            Subject = "Thể dục",
                            Teacher = "GV07",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-97",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.217",
                            Slot = 1,
                            Subject = "Toán học",
                            Teacher = "GV08",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-98",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.218",
                            Slot = 2,
                            Subject = "Ngữ văn",
                            Teacher = "GV09",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-99",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.219",
                            Slot = 3,
                            Subject = "Tiếng Anh",
                            Teacher = "GV10",
                            Term = "2024-2025"
                        },
                        new
                        {
                            Id = "sch-100",
                            ClassName = "1B1",
                            DayOfWeek = "Thứ 6",
                            Room = "P.200",
                            Slot = 4,
                            Subject = "Khoa học",
                            Teacher = "GV11",
                            Term = "2024-2025"
                        });
                });

            modelBuilder.Entity("MyFSchools.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActiveChildId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveChildId")
                        .IsUnique()
                        .HasFilter("[ActiveChildId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "u-001",
                            Email = "nguyenvana@myfschools.com",
                            Password = "Password123",
                            Phone = "0912345678"
                        },
                        new
                        {
                            Id = "u-002",
                            Email = "tranthib@myfschools.com",
                            Password = "Password123",
                            Phone = "0923456789"
                        },
                        new
                        {
                            Id = "u-003",
                            Email = "lehongc@myfschools.com",
                            Password = "Password123",
                            Phone = "0934567890"
                        });
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Child", b =>
                {
                    b.HasOne("MyFSchools.Api.Models.User", "User")
                        .WithMany("Children")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFSchools.Api.Models.ChildClub", b =>
                {
                    b.HasOne("MyFSchools.Api.Models.Child", "Child")
                        .WithMany("ChildClubs")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFSchools.Api.Models.Club", "Club")
                        .WithMany("ChildClubs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Form", b =>
                {
                    b.HasOne("MyFSchools.Api.Models.Child", "Child")
                        .WithMany("Forms")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyFSchools.Api.Models.User", "User")
                        .WithMany("Forms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Grade", b =>
                {
                    b.HasOne("MyFSchools.Api.Models.Child", "Child")
                        .WithMany("Grades")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Notification", b =>
                {
                    b.HasOne("MyFSchools.Api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFSchools.Api.Models.User", b =>
                {
                    b.HasOne("MyFSchools.Api.Models.Child", "ActiveChild")
                        .WithOne()
                        .HasForeignKey("MyFSchools.Api.Models.User", "ActiveChildId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ActiveChild");
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Child", b =>
                {
                    b.Navigation("ChildClubs");

                    b.Navigation("Forms");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("MyFSchools.Api.Models.Club", b =>
                {
                    b.Navigation("ChildClubs");
                });

            modelBuilder.Entity("MyFSchools.Api.Models.User", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Forms");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
